version: "3.2"
services:
  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    platform: linux/x86_64
    volumes:
      - ${DEVSTACK_WORKSPACE}/shared:/shared
  mongo:
    volumes:
      - ${DEVSTACK_WORKSPACE}/shared:/shared
    ports:
      - "27017:27017"
  lms:
    environment:
      OPENEDX_RELEASE: "juniper:master"
      COMPOSE_PROJECT_NAME: "alw"
      DEVSTACK_WORKSPACE: "/Users/qasim.gulzar/IdeaProjects/ALW"
    volumes:
      - ${DEVSTACK_WORKSPACE}/etc/lms.yml:/edx/etc/lms.yml
      - ${DEVSTACK_WORKSPACE}/etc/studio.yml:/edx/etc/studio.yml
      - ${DEVSTACK_WORKSPACE}/etc/revisions.yml:/edx/etc/revisions.yml
      - ${DEVSTACK_WORKSPACE}/shared:/shared
  mysql:
    ports:
      - "3506:3306"
    volumes:
      - ${DEVSTACK_WORKSPACE}/shared:/shared
